# Generated by Django 5.1.5 on 2026-02-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_myplaya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_pg',
            new_name='RequestCall',
        ),
    ]
