# Generated by Django 5.1.5 on 2026-02-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_myplaya', '0002_rename_home_pg_requestcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcall',
            options={'verbose_name': 'Request Call', 'verbose_name_plural': 'Request Call'},
        ),
    ]
