# Generated by Django 5.1.5 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_myplaya', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('pharmacy_name', models.CharField(max_length=150)),
                ('pharmacy_phone_number', models.CharField(max_length=20)),
                ('rx_number', models.CharField(max_length=100)),
                ('medicine_first_letters', models.CharField(max_length=10)),
                ('medicine_needed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfer RX',
                'verbose_name_plural': 'Transfer RX',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
    ]
