# Generated by Django 5.1.5 on 2026-02-19 10:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_myplaya', '0005_transferrx_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcall',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='transferrx',
            name='pharmacy_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Enter a valid US pharmacy phone number'}, max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='transferrx',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Enter a valid US phone number'}, max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='transferrx',
            name='rx_number',
            field=models.CharField(max_length=3),
        ),
    ]
